# Generated by Django 3.0.6 on 2020-05-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvm_forms', '0002_auto_20200521_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='komisijos_narys',
        ),
    ]
