# Generated by Django 3.0.6 on 2020-05-21 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pvm_forms', '0004_auto_20200521_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='data',
            new_name='formos_data',
        ),
        migrations.AddField(
            model_name='form',
            name='pardavejas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='pardavimo_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='serija',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
